_welcome:
    path:     /
    defaults: { _controller: SkilinskasCalcBundle:Welcome:index }
_calculator:
    path:     /calc/add/{x}/{y}/
    defaults: { _controller: SkilinskasCalcBundle:Calculator:add, x: 0, y: 0 }

