<?php

namespace Skilinskas\DiaryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends EntityRepository
{
    public function findAllFiltered($subject = null, $date_from = null, $date_to = null)
    {
        if ($date_from == null) {
            $date_from = date('Y-m-d', strtotime('-7 days'));
        }
        if ($date_to == null) {
            $date_to = date("Y-m-d");
        }
        if ($subject == null) {
            $sql = <<<SQL
SELECT g FROM SkilinskasDiaryBundle:Grade g
WHERE g.date >= '$date_from' AND g.date <= '$date_to'
ORDER BY g.date DESC
SQL;
        } else {
            $sql = <<<SQL
SELECT g FROM SkilinskasDiaryBundle:Grade g
WHERE g.date >= '$date_from' AND g.date <= '$date_to' AND g.subject = $subject
ORDER BY g.date DESC
SQL;
        }

        return $this->getEntityManager()
            ->createQuery(
                $sql
            )
            ->getResult();
    }
}
